package com.testpilot.testing.entity;

public enum TestRunStatus {
    PENDING,
    INTAKE,
    MAPPING_CODEBASE,
    PLANNING_TESTS,
    ANALYZING,
    GENERATING_TESTS,
    GENERATING_UNIT_TESTS,
    GENERATING_MODULE_TESTS,
    GENERATING_INTEGRATION_TESTS,
    REVIEWING_TESTS,
    AWAITING_APPROVAL,
    RUNNING_TESTS,
    ANALYZING_FAILURES,
    REPORTING,
    COMPLETED,
    FAILED,
    REJECTED
}
