package com.testpilot.repository;

import com.testpilot.common.exception.InvalidRequestException;
import com.testpilot.common.validation.RepositoryPathPolicy;
import com.testpilot.repository.connector.RepositoryFileContent;
import com.testpilot.repository.connector.RepositoryTreeEntry;
import com.testpilot.repository.entity.BuildSystem;
import com.testpilot.repository.entity.RepositoryArtifactKind;
import com.testpilot.repository.service.RepositoryCatalogPolicy;
import org.junit.jupiter.api.Test;

import java.nio.charset.StandardCharsets;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class RepositoryCatalogPolicyTest {

    private final RepositoryCatalogPolicy policy =
            new RepositoryCatalogPolicy(new RepositoryPathPolicy());

    @Test
    void selectsMultipleLanguagesAndReadOnlyManifests() {
        for (String path : List.of("app.py", "web/App.tsx", "server/index.js", "main.go", "src/lib.rs",
                "App.java", "src/app.cs", "app.rb", "src/main.cpp", "schema.sql", "App.vue")) {
            assertEquals(RepositoryArtifactKind.SOURCE_CODE,
                    policy.classify(new RepositoryTreeEntry(path, "sha", 20, "blob")).orElseThrow(), path);
        }
        for (String path : List.of("tests/test_app.py", "web/app.test.ts", "main_test.go", "evaluation/benchmark/project/src/main/java/App.java")) {
            assertEquals(RepositoryArtifactKind.EXISTING_TEST,
                    policy.classify(new RepositoryTreeEntry(path, "sha", 20, "blob")).orElseThrow(), path);
        }
        for (String path : List.of("package.json", "pyproject.toml", "go.mod", "Cargo.toml")) {
            assertEquals(RepositoryArtifactKind.BUILD_MANIFEST,
                    policy.classify(new RepositoryTreeEntry(path, "sha", 20, "blob")).orElseThrow(), path);
        }
        assertEquals("Python", RepositoryCatalogPolicy.language("src/app.py"));
    }

    @Test
    void reportsDeclaredTestScriptsWithoutRunningThem() {
        var artifact = policy.decode(new RepositoryFileContent("web/package.json", "sha",
                "{\"scripts\":{\"test\":\"echo untrusted\"}}".getBytes(StandardCharsets.UTF_8)),
                RepositoryArtifactKind.BUILD_MANIFEST);
        var context = policy.buildContexts(List.of(artifact)).get(0);
        assertEquals("Node.js", context.ecosystem());
        assertEquals("web/package.json", context.path());
        assertTrue(context.testCommandHint().contains("not validated"));
    }

    @Test
    void excludesGeneratedDependenciesSecretsAndUnknownAssets() {
        for (String path : List.of("node_modules/a/index.js", ".venv/lib/app.py", "web/.next/app.js",
                "benchmark/mutants/src/main/java/App.java", "src/generated/client.ts", "app.min.js",
                "package-lock.json", "foo/.env.local", "../app.py", "assets/photo.png", "unknown.xyz")) {
            assertTrue(policy.classify(new RepositoryTreeEntry(path, "sha", 20, "blob")).isEmpty(), path);
        }
        assertTrue(policy.classify(new RepositoryTreeEntry("app.py", "sha", 524289, "blob")).isEmpty());
        assertTrue(policy.classify(new RepositoryTreeEntry("app.py", "sha", 10, "commit")).isEmpty());
        assertThrows(InvalidRequestException.class, () -> policy.decode(new RepositoryFileContent(
                "client.go", "sha", "// Code generated by protoc. DO NOT EDIT.\npackage client".getBytes(StandardCharsets.UTF_8)),
                RepositoryArtifactKind.SOURCE_CODE));
    }

    @Test
    void shouldClassifyOnlySupportedTextInputsAndDetectBuildSystem() {
        RepositoryTreeEntry pom = new RepositoryTreeEntry("pom.xml", "1", 10, "blob");
        RepositoryTreeEntry source = new RepositoryTreeEntry(
                "module/src/main/java/com/example/App.java", "2", 10, "blob");
        RepositoryTreeEntry output = new RepositoryTreeEntry(
                "target/classes/App.class", "3", 10, "blob");

        assertEquals(RepositoryArtifactKind.BUILD_MANIFEST, policy.classify(pom).orElseThrow());
        assertEquals(RepositoryArtifactKind.JAVA_SOURCE, policy.classify(source).orElseThrow());
        assertTrue(policy.classify(output).isEmpty());

        var artifact = policy.decode(
                new RepositoryFileContent("pom.xml", "1", "<project/>".getBytes(StandardCharsets.UTF_8)),
                RepositoryArtifactKind.BUILD_MANIFEST);
        assertEquals(BuildSystem.MAVEN, policy.detectBuildSystem(List.of(artifact)));
    }

    @Test
    void shouldRejectBinaryAndCredentialLikeContent() {
        assertThrows(InvalidRequestException.class, () -> policy.decode(
                new RepositoryFileContent("src/main/java/App.java", "1", new byte[]{0, 1, 2}),
                RepositoryArtifactKind.JAVA_SOURCE));
        assertThrows(InvalidRequestException.class, () -> policy.decode(
                new RepositoryFileContent(
                        "src/main/java/App.java",
                        "1",
                        "// ghp_abcdefghijklmnopqrstuvwxyz123456".getBytes(StandardCharsets.UTF_8)),
                RepositoryArtifactKind.JAVA_SOURCE));
    }
}
